[project]
name = "python-experimentation-sandbox"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = [
    "experiments/2026-04-16-minio-libre",
    "experiments/2026-04-22-gotenberg-benchmark",
    "experiments/2026-04-23-gotenberg-merge-pdf",
    "scripts",
    "experiments/2026-05-14-pwdlib-bcrypt-hashing",
    "experiments/2026-05-22-playwright-shared-browser-info",
    "experiments/2026-06-09-fast-streams-rabbitmq",
    "experiments/2026-06-18-smtp",
]
